### ISSUE TITLE
Can we have this on regular css stylesheets?

### ISSUE THREAD

**Issue by gaizkamg** [shubhsnov/intelligent-scss-hints#1]
Hi, I notice that if I save my regular css as scss I can use the extension with my classes and ids and is very usefull.
Can we modify the plugin so we can use it on regular css files?

**Comment by shubhsnov** [comment]
Thanks, a lot for trying and the feedback. 

As for CSS, doesn't brackets already have that feature? 
CSSCodeHints are directly supported in brackets. 

Let me know if there is anything specific you need help with.

**Comment by gaizkamg** [comment]
CSS Code Hints only works on the html file, not in the css

**Comment by gaizkamg** [comment]
Ey, I've found another plugin that does what I want:
https://github.com/Wikunia/brackets-jQuinter
Will use yours with SCSS, thanks!

**Comment by shubhsnov** [comment]
Ah great. There is a lot of stuff in the pipeline, but I am glad you got an early fix. 
And since you liked the extension, do recommend to other people as well. The more it gains popularity, the more it is used, the more It'll help me improve it.

**Comment by ezenyhk** [comment]
> Ey, I've found another plugin that does what I want:
> https://github.com/Wikunia/brackets-jQuinter
> Will use yours with SCSS, thanks!

It is really helpful! Thank you!
